-- PacaControl: esquema inicial para Supabase/Postgres.
-- Esta migración está pensada para ejecutarse una sola vez desde SQL Editor
-- o mediante `supabase db push`.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  name text not null check (char_length(trim(name)) between 1 and 80),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (owner_id, slug),
  unique (owner_id, name)
);

create table if not exists public.bales (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  bale_number bigint generated by default as identity unique,
  code text generated always as ('PAC-' || lpad(bale_number::text, 4, '0')) stored unique,
  purchase_date date not null default current_date,
  purchase_cost numeric(12, 2) not null check (purchase_cost > 0),
  transport_cost numeric(12, 2) not null default 0 check (transport_cost >= 0),
  other_expenses numeric(12, 2) not null default 0 check (other_expenses >= 0),
  received_pieces integer not null check (received_pieces > 0),
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.bale_inventory (
  id uuid primary key default gen_random_uuid(),
  bale_id uuid not null references public.bales (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete restrict,
  received_quantity integer not null check (received_quantity > 0),
  sold_quantity integer not null default 0 check (sold_quantity >= 0),
  damaged_quantity integer not null default 0 check (damaged_quantity >= 0),
  available_quantity integer generated always as (received_quantity - sold_quantity - damaged_quantity) stored,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (bale_id, category_id),
  check (sold_quantity + damaged_quantity <= received_quantity)
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  phone text check (char_length(phone) <= 30),
  is_priority boolean not null default false,
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete set null,
  payment_method text not null check (payment_method in ('cash', 'transfer', 'card', 'other')),
  sold_at timestamptz not null default timezone('utc', now()),
  total numeric(12, 2) not null default 0 check (total >= 0),
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price > 0),
  line_total numeric(12, 2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sale_item_allocations (
  id uuid primary key default gen_random_uuid(),
  sale_item_id uuid not null references public.sale_items (id) on delete cascade,
  bale_inventory_id uuid not null references public.bale_inventory (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (sale_item_id, bale_inventory_id)
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  bale_id uuid references public.bales (id) on delete set null,
  concept text not null check (char_length(trim(concept)) between 1 and 160),
  amount numeric(12, 2) not null check (amount > 0),
  expense_date date not null default current_date,
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.damaged_products (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  bale_inventory_id uuid not null references public.bale_inventory (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  reason text not null check (char_length(trim(reason)) between 1 and 500),
  reported_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists bales_owner_purchase_date_idx on public.bales (owner_id, purchase_date desc);
create index if not exists bale_inventory_bale_id_idx on public.bale_inventory (bale_id);
create index if not exists bale_inventory_category_id_idx on public.bale_inventory (category_id);
create index if not exists customers_owner_name_idx on public.customers (owner_id, name);
create index if not exists sales_owner_sold_at_idx on public.sales (owner_id, sold_at desc);
create index if not exists sale_items_sale_id_idx on public.sale_items (sale_id);
create index if not exists sale_items_category_id_idx on public.sale_items (category_id);
create index if not exists expenses_owner_expense_date_idx on public.expenses (owner_id, expense_date desc);
create index if not exists damaged_products_inventory_id_idx on public.damaged_products (bale_inventory_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.create_profile_and_categories()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do nothing;

  insert into public.categories (owner_id, slug, name)
  values
    (new.id, 'shirts', 'Camisas'),
    (new.id, 'blouses', 'Blusas'),
    (new.id, 'pants', 'Pantalones'),
    (new.id, 'skirts', 'Faldas'),
    (new.id, 'dresses', 'Vestidos'),
    (new.id, 'kids', 'Ropa infantil'),
    (new.id, 'other', 'Otros')
  on conflict (owner_id, slug) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.create_profile_and_categories();

create or replace function public.register_sale(
  p_category_id uuid,
  p_quantity integer,
  p_unit_price numeric,
  p_payment_method text,
  p_customer_id uuid default null,
  p_sold_at timestamptz default timezone('utc', now()),
  p_notes text default null
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_sale_item_id uuid;
  v_inventory record;
  v_remaining integer := p_quantity;
  v_allocated integer;
  v_available integer;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para registrar una venta.';
  end if;

  if p_quantity is null or p_quantity < 1 then
    raise exception 'La cantidad debe ser mayor que cero.';
  end if;

  if p_unit_price is null or p_unit_price <= 0 then
    raise exception 'El precio por pieza debe ser mayor que cero.';
  end if;

  if p_payment_method not in ('cash', 'transfer', 'card', 'other') then
    raise exception 'Método de pago inválido.';
  end if;

  if not exists (
    select 1 from public.categories
    where id = p_category_id and owner_id = auth.uid()
  ) then
    raise exception 'La categoría no existe o no te pertenece.';
  end if;

  if p_customer_id is not null and not exists (
    select 1 from public.customers
    where id = p_customer_id and owner_id = auth.uid()
  ) then
    raise exception 'El cliente no existe o no te pertenece.';
  end if;

  select coalesce(sum(bi.available_quantity), 0)
  into v_available
  from public.bale_inventory bi
  join public.bales b on b.id = bi.bale_id
  where b.owner_id = auth.uid()
    and bi.category_id = p_category_id;

  if v_available < p_quantity then
    raise exception 'Inventario insuficiente: hay % piezas disponibles.', v_available;
  end if;

  insert into public.sales (owner_id, customer_id, payment_method, sold_at, total, notes)
  values (auth.uid(), p_customer_id, p_payment_method, coalesce(p_sold_at, timezone('utc', now())), p_quantity * p_unit_price, p_notes)
  returning * into v_sale;

  insert into public.sale_items (sale_id, category_id, quantity, unit_price)
  values (v_sale.id, p_category_id, p_quantity, p_unit_price)
  returning id into v_sale_item_id;

  for v_inventory in
    select bi.id, bi.available_quantity
    from public.bale_inventory bi
    join public.bales b on b.id = bi.bale_id
    where b.owner_id = auth.uid()
      and bi.category_id = p_category_id
      and bi.available_quantity > 0
    order by b.purchase_date, b.created_at, bi.created_at
    for update of bi
  loop
    exit when v_remaining = 0;

    v_allocated := least(v_remaining, v_inventory.available_quantity);

    update public.bale_inventory
    set sold_quantity = sold_quantity + v_allocated
    where id = v_inventory.id;

    insert into public.sale_item_allocations (sale_item_id, bale_inventory_id, quantity)
    values (v_sale_item_id, v_inventory.id, v_allocated);

    v_remaining := v_remaining - v_allocated;
  end loop;

  if v_remaining > 0 then
    raise exception 'No fue posible reservar todo el inventario solicitado.';
  end if;

  return v_sale;
end;
$$;

create or replace function public.register_damaged_product(
  p_bale_inventory_id uuid,
  p_quantity integer,
  p_reason text,
  p_reported_at timestamptz default timezone('utc', now())
)
returns public.damaged_products
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inventory public.bale_inventory;
  v_damaged public.damaged_products;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para registrar una merma.';
  end if;

  if p_quantity is null or p_quantity < 1 then
    raise exception 'La cantidad debe ser mayor que cero.';
  end if;

  select bi.* into v_inventory
  from public.bale_inventory bi
  join public.bales b on b.id = bi.bale_id
  where bi.id = p_bale_inventory_id
    and b.owner_id = auth.uid()
  for update of bi;

  if not found then
    raise exception 'El inventario no existe o no te pertenece.';
  end if;

  if v_inventory.available_quantity < p_quantity then
    raise exception 'Inventario insuficiente: hay % piezas disponibles.', v_inventory.available_quantity;
  end if;

  update public.bale_inventory
  set damaged_quantity = damaged_quantity + p_quantity
  where id = v_inventory.id;

  insert into public.damaged_products (owner_id, bale_inventory_id, quantity, reason, reported_at)
  values (auth.uid(), p_bale_inventory_id, p_quantity, p_reason, coalesce(p_reported_at, timezone('utc', now())))
  returning * into v_damaged;

  return v_damaged;
end;
$$;

create or replace view public.inventory_summary
with (security_invoker = true)
as
select
  c.id as category_id,
  c.owner_id,
  c.slug,
  c.name,
  coalesce(sum(bi.received_quantity), 0)::integer as received_pieces,
  coalesce(sum(bi.sold_quantity), 0)::integer as sold_pieces,
  coalesce(sum(bi.damaged_quantity), 0)::integer as damaged_pieces,
  coalesce(sum(bi.available_quantity), 0)::integer as available_pieces
from public.categories c
left join public.bale_inventory bi on bi.category_id = c.id
group by c.id, c.owner_id, c.slug, c.name;

create or replace view public.bale_summary
with (security_invoker = true)
as
select
  b.*,
  coalesce(sum(bi.sold_quantity), 0)::integer as sold_pieces,
  coalesce(sum(bi.damaged_quantity), 0)::integer as damaged_pieces,
  coalesce(sum(bi.available_quantity), 0)::integer as available_pieces,
  b.purchase_cost + b.transport_cost + b.other_expenses as total_investment
from public.bales b
left join public.bale_inventory bi on bi.bale_id = b.id
group by b.id;

create or replace view public.customer_summary
with (security_invoker = true)
as
select
  c.*,
  count(s.id)::integer as purchases,
  coalesce(sum(s.total), 0)::numeric(12, 2) as total_spent
from public.customers c
left join public.sales s on s.customer_id = c.id
group by c.id;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories
for each row execute procedure public.set_updated_at();

drop trigger if exists bales_set_updated_at on public.bales;
create trigger bales_set_updated_at before update on public.bales
for each row execute procedure public.set_updated_at();

drop trigger if exists bale_inventory_set_updated_at on public.bale_inventory;
create trigger bale_inventory_set_updated_at before update on public.bale_inventory
for each row execute procedure public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers
for each row execute procedure public.set_updated_at();

drop trigger if exists sales_set_updated_at on public.sales;
create trigger sales_set_updated_at before update on public.sales
for each row execute procedure public.set_updated_at();

drop trigger if exists expenses_set_updated_at on public.expenses;
create trigger expenses_set_updated_at before update on public.expenses
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.bales enable row level security;
alter table public.bale_inventory enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.sale_item_allocations enable row level security;
alter table public.expenses enable row level security;
alter table public.damaged_products enable row level security;

create policy "Users can read their profile" on public.profiles
for select to authenticated using ((select auth.uid()) = id);
create policy "Users can update their profile" on public.profiles
for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "Users manage their categories" on public.categories
for all to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "Users manage their bales" on public.bales
for all to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "Users manage their inventory" on public.bale_inventory
for all to authenticated
using (exists (select 1 from public.bales b where b.id = bale_id and b.owner_id = (select auth.uid())))
with check (exists (select 1 from public.bales b where b.id = bale_id and b.owner_id = (select auth.uid())));
create policy "Users manage their customers" on public.customers
for all to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "Users read their sales" on public.sales
for select to authenticated using ((select auth.uid()) = owner_id);
create policy "Users read their sale items" on public.sale_items
for select to authenticated
using (exists (select 1 from public.sales s where s.id = sale_id and s.owner_id = (select auth.uid())));
create policy "Users read their sale allocations" on public.sale_item_allocations
for select to authenticated
using (
  exists (
    select 1
    from public.sale_items si
    join public.sales s on s.id = si.sale_id
    where si.id = sale_item_id and s.owner_id = (select auth.uid())
  )
);
create policy "Users manage their expenses" on public.expenses
for all to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "Users read their damaged products" on public.damaged_products
for select to authenticated using ((select auth.uid()) = owner_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.categories, public.bales, public.bale_inventory, public.customers, public.expenses to authenticated;
grant select on public.sales, public.sale_items, public.sale_item_allocations, public.damaged_products to authenticated;
grant select on public.inventory_summary, public.bale_summary, public.customer_summary to authenticated;
grant execute on function public.register_sale(uuid, integer, numeric, text, uuid, timestamptz, text) to authenticated;
grant execute on function public.register_damaged_product(uuid, integer, text, timestamptz) to authenticated;
